language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text  --coverage-clover=coverage.clover
